
var data = {
   "farm":{
      "bot000001":{
         "status":"offline",
         "problems":{
            "extruderFanFailure":false,
            "tornInsulation":false,
            "wornYCarriage":false,
            "xEndstopFailure":false,
            "xStepperFailure":false,
            "hotEndFailure":false
         },
         "type":"Replicator 2X",
         "name":"Sharon",
         "events":{
            "ovalHoles":0,
            "highResUnderExtrusion":0,
            "underExtrusion":0,
            "layerShift":0
         }
      },
      "bot000002":{
         "status":"faulty",
         "problems":{
            "extruderFanFailure":false,
            "tornInsulation":false,
            "wornYCarriage":false,
            "xEndstopFailure":false,
            "xStepperFailure":false,
            "hotEndFailure":false
         },
         "type":"Replicator 2X",
         "name":"Brandon",
         "events":{
            "ovalHoles":0,
            "highResUnderExtrusion":0,
            "underExtrusion":0,
            "layerShift":0
         }
      },
      "bot000003":{
         "status":"online",
         "problems":{
            "extruderFanFailure":false,
            "tornInsulation":false,
            "wornYCarriage":false,
            "xEndstopFailure":false,
            "xStepperFailure":false,
            "hotEndFailure":true
         },
         "type":"Replicator 2X",
         "name":"Phillip",
         "events":{
            "ovalHoles":1,
            "highResUnderExtrusion":0,
            "underExtrusion":0,
            "layerShift":2
         }
      }
   }
}